# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

名字: pmd

on:
  push:
    分支: [ "master" ]
  pull_request:
    分支: [ "master" ]
  schedule:
    - cron: '33 5 * * 6'

permissions:
  contents: read

作業:
  pmd-code-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: 撰寫 # for github/codeql-action/upload-sarif to upload SARIF results
      操作: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - 名字: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - 名字: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@967a81f8b657c87f7c3e96b62301cb1a48efef29
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false
      - 名字: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pmd-report.sarif
